# Site settings
title: Anas Munir 
header-img: img/header.jpg
email: anas.munir.92@gmail.com
copyright_name: Your/Project/Corporate Name
description: "This is my resume/portfolio and a blog"
baseurl: ""
url: "http://anasmunir.github.io"
twitter_username: SBootstrap
github_username:  AnasMunir
facebook_username:  anas.muneer.92
email_username:  anas.munir.92@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
